/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiErrorBody: {
            code: string;
            message: string;
        };
        /** @description OpenAPI 全局错误组件。 */
        Error: {
            code: string;
            message: string;
        };
        GroupDto: {
            description?: string | null;
            id: string;
            /** Format: int64 */
            intervalMs: number;
            name: string;
        };
        /** @description v1 节点响应：脱敏 config + connection_status。 */
        NodeDto: {
            config: unknown;
            connectionStatus?: unknown;
            id: string;
            kind: string;
            name: string;
            pluginName: string;
            state: string;
        };
        /** @description 通用分页查询参数。page 默认 1，page_size 默认 50 clamp [1, 1000]。 */
        PageParams: {
            /** @description 组 ID 过滤，仅 tags */
            group_id?: string | null;
            /** @description 节点类型过滤，仅 nodes */
            kind?: string | null;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            page_size?: number;
            /** @description name 子串过滤（大小写不敏感），仅 nodes/groups/tags */
            q?: string | null;
        };
        /** @description 分页信封，v1 列表端点专用。 */
        Page_GroupDto: {
            items: {
                description?: string | null;
                id: string;
                /** Format: int64 */
                intervalMs: number;
                name: string;
            }[];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int64 */
            total: number;
        };
        /** @description 分页信封，v1 列表端点专用。 */
        Page_NodeDto: {
            items: {
                config: unknown;
                connectionStatus?: unknown;
                id: string;
                kind: string;
                name: string;
                pluginName: string;
                state: string;
            }[];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int64 */
            total: number;
        };
        /** @description 分页信封，v1 列表端点专用。 */
        Page_RuleDto: {
            items: {
                /** @description RuleAction 枚举如实序列化为 JSON */
                action: Record<string, never>;
                /** Format: int64 */
                clearMs: number;
                condition: Record<string, never>;
                enabled: boolean;
                /** Format: int64 */
                forMs: number;
                id: string;
                name: string;
                runtime: components["schemas"]["RuleRuntime"];
                /** @description RuleSource 结构体如实序列化为 JSON */
                source: Record<string, never>;
            }[];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int64 */
            total: number;
        };
        /** @description 分页信封，v1 列表端点专用。 */
        Page_TagDto: {
            items: {
                address: string;
                attr: string;
                dataType?: string | null;
                description?: string | null;
                groupId: string;
                id: string;
                name: string;
            }[];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int64 */
            total: number;
        };
        /** @description 分页信封，v1 列表端点专用。 */
        Page_UserDto: {
            items: {
                createdAt: string;
                id: string;
                role: string;
                updatedAt: string;
                username: string;
            }[];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int64 */
            total: number;
        };
        /** @description 分页信封，v1 列表端点专用。 */
        Page_ValueDto: {
            items: {
                available: boolean;
                groupId: string;
                name: string;
                tagId: string;
                /** Format: int64 */
                ts?: number | null;
                value: unknown;
            }[];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int64 */
            total: number;
        };
        RuleDto: {
            /** @description RuleAction 枚举如实序列化为 JSON */
            action: Record<string, never>;
            /** Format: int64 */
            clearMs: number;
            condition: Record<string, never>;
            enabled: boolean;
            /** Format: int64 */
            forMs: number;
            id: string;
            name: string;
            runtime: components["schemas"]["RuleRuntime"];
            /** @description RuleSource 结构体如实序列化为 JSON */
            source: Record<string, never>;
        };
        RuleRuntime: {
            /** Format: int64 */
            fireCount: number;
            fired: boolean;
            lastValue?: unknown;
        };
        TagDto: {
            address: string;
            attr: string;
            dataType?: string | null;
            description?: string | null;
            groupId: string;
            id: string;
            name: string;
        };
        UserDto: {
            createdAt: string;
            id: string;
            role: string;
            updatedAt: string;
            username: string;
        };
        /** @description /nodes/:id/values 响应中的单个 tag 值。 */
        ValueDto: {
            available: boolean;
            groupId: string;
            name: string;
            tagId: string;
            /** Format: int64 */
            ts?: number | null;
            value: unknown;
        };
        /** @description WS 客户端 → 服务器帧。 */
        WsClientFrame: {
            token?: string | null;
            /** @enum {string} */
            type: "auth";
        } | {
            /** @enum {string} */
            type: "ping";
        } | {
            /** @enum {string} */
            type: "pong";
        } | {
            groupIds?: string[] | null;
            nodeIds?: string[] | null;
            topics: string[];
            /** @enum {string} */
            type: "subscribe";
        } | {
            topics: string[];
            /** @enum {string} */
            type: "unsubscribe";
        };
        /** @description nodes 快照帧中的节点。 */
        WsNodeSnapshot: {
            connectionStatus?: unknown;
            id: string;
            kind: string;
            name: string;
            pluginName: string;
            state: string;
        };
        /** @description WS 服务器 → 客户端帧。 */
        WsServerFrame: {
            build_date: string;
            features: string[];
            /** @enum {string} */
            type: "hello";
            version: string;
        } | {
            message?: string | null;
            success: boolean;
            /** @enum {string} */
            type: "auth";
        } | {
            /** @enum {string} */
            type: "ping";
        } | {
            /** @enum {string} */
            type: "pong";
        } | {
            data: components["schemas"]["WsValuesData"];
            /** @enum {string} */
            type: "values";
        } | {
            nodes: components["schemas"]["WsNodeSnapshot"][];
            /** @enum {string} */
            type: "nodes";
        } | {
            message: string;
            /** @enum {string} */
            type: "error";
        };
        /** @description 单个 tag 的值（DataValue 编码与 REST 完全一致）。 */
        WsTagValue: {
            tagId: string;
            tagName?: string | null;
            value: unknown;
        };
        /** @description values 帧数据体。 */
        WsValuesData: {
            groupId: string;
            groupName?: string | null;
            nodeId: string;
            nodeName?: string | null;
            values: components["schemas"]["WsTagValue"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
