[workspace]
resolver = "2"
members = [
    "gateway/gateway-sdk",
    "gateway/gateway-core",
    "gateway/gateway-server",
    "gateway/gateway-plugins/plugin-sim",
    "gateway/gateway-plugins/plugin-mqtt",
    "gateway/gateway-plugins/plugin-modbus-tcp",
    "gateway/gateway-plugins/plugin-modbus-rtu",
    "gateway/gateway-plugins/plugin-opcua",
    "gateway/gateway-plugins/plugin-virb",
]
